### ISSUE TITLE
希望在测试时期能够让badjs的错误更加明显

### ISSUE THREAD

**Issue by AsiamCn** [iv-web/badjs-ivweb#2]
有些badjs的错误在测试期间出现了，但是因为表现没有那么明显，可能被忽略掉。

比如：点击用户个人头像跳转资料卡，可能测试人员在测试期间点过这个地方，但是因为没有响应，测试人员可能以为是没有这个功能。而实际上开发实现了这个功能，但是实现上报了错误，导致功能不能正常执行。

这种错误在测试期间就被忽略了，直到上线看到大量的badjs上报才会意识到。

**Comment by Leo555** [comment]
暂时没有找到合适的方法，开发者可以通过监听错误的方式来关注
